export const courses = [
  {
    id: 1,
    title: "Monitoring the Future Study: Drug Use(1975-2024)",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 2,
    title: "Psychotropic Medications and their Uses",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 3,
    title: "Understanding Workers rights Under OSHA",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 4,
    title: "A Citizen's Guide to Elder Abuse in California",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1516733725897-1aa73b87c8e8?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 5,
    title: "California Mandated Reporting Requirements",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 6,
    title: "How Drugs Impact the Brain and Behavior",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1559757175-5700dde675bc?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 7,
    title: "Understanding Depression",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1518152006812-edab29b069ac?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 8,
    title: "Understanding Schizophrenia: Symptoms and Treatments",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1527137342181-19aab11a8ee1?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 9,
    title: "Understanding Sexual Orientation",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 10,
    title: "OSHA Guidelines for Preventing Workplace Violence",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 11,
    title: "Emergency Preparedness for Various Disasters",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1504439468489-c8920d796a29?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 12,
    title: "Eating Guidelines for Managing Diabetes",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 13,
    title: "Preventing and Reporting Elder Adult Abuse(Cali.)",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1447452001602-7090c7ab2db3?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 14,
    title: "Preventing Workplace Violence in Healthcare",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 15,
    title: "Basic Medication Administration",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 16,
    title: "Identifying and Treating Attention Deficit Hyperactivity Disorder",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 17,
    title: "Understanding Autism Spectrum Disorder (ASD)",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1503454537195-1dcabb73ffb9?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 18,
    title: "Implementing Community-Based Fall Prevention",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Start Learning",
    image: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 19,
    title: "Understanding Drug Abuse and Addiction",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&q=80&w=800",
  },
  {
    id: 20,
    title: "How to Plan for Workplace Emergencies",
    instructor: "Excel Community Living",
    category: "Continuing Educations Courses",
    price: "Enroll Now",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=800",
  },
];

export const testimonials = [
  {
    id: 1,
    text: "The online platform made renewing my Adult residential facility administrators (ARF) certification a breeze. The courses are flexible, comprehensive, and relevant, allowing me to complete all requirements online efficiently. Highly recommend for ARF needing convenient CE options.",
    author: "Satisfied Client",
    role: "ARF Administrator",
  },
  {
    id: 2,
    text: "The online courses are a lifesaver for busy Adult residential facility administrators (ARF). The platform is straightforward, secure, and offers courses at your own pace. Completed my CE requirements with ease and gained valuable knowledge. Great for any ARF looking to renew their certification.",
    author: "Satisfied Client",
    role: "ARF Administrator",
  },
  {
    id: 3,
    text: "Impressed with the range of online courses. User-friendly, affordable, and informative, allowing for your CE to be completed online. An excellent resource for Adult residential facility administrators (ARF) seeking convenient continuing education.",
    author: "Satisfied Client",
    role: "ARF Administrator",
  },
];

export const contactInfo = {
  phone: "(661) 600-5354",
  email: "admin@excelcommunitylivinginc.com",
  address: "United States",
};

export const heroContent = {
  badge: "Waiting To Be Approved",
  title: "Continuing Education for Adult residential facility administrators (ARF)",
  description: "Welcome to the online 24 hour resource designed to help you get the required continuing education classes needed to renew your certification. Quick, affordable, fully online. Enroll now for easy recertification.",
};
